# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-07 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u6c49', max_length=20, verbose_name='\u6c11\u65cf')),
            ],
            options={
                'verbose_name': '\u6c11\u65cf\u4fe1\u606f',
                'verbose_name_plural': '\u6c11\u65cf\u4fe1\u606f',
            },
        ),
    ]
