# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-07 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comminfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u95e8\u7981\u8bbe\u5907', max_length=50, verbose_name='\u8bbe\u5907\u7c7b\u578b\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u8bbe\u5907\u7c7b\u578b\u7ba1\u7406',
                'verbose_name_plural': '\u8bbe\u5907\u7c7b\u578b\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Sys_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='\u95e8\u7981\u7cfb\u7edf', max_length=50, verbose_name='\u7cfb\u7edf\u6a21\u5757\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u7cfb\u7edf\u6a21\u5757\u7ba1\u7406',
                'verbose_name_plural': '\u7cfb\u7edf\u6a21\u5757\u7ba1\u7406',
            },
        ),
    ]
