# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100, verbose_name='\u673a\u6784\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u673a\u6784\u7ba1\u7406',
                'verbose_name_plural': '\u673a\u6784\u7ba1\u7406',
            },
        ),
    ]
