# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-07 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comminfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_for_personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', models.CharField(default='', max_length=10, verbose_name='\u5361\u7247\u7269\u7406\u53f7')),
            ],
            options={
                'verbose_name': '\u4eba\u5458\u53d1\u5361',
                'verbose_name_plural': '\u4eba\u5458\u53d1\u5361',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=100, verbose_name='\u673a\u6784\u540d\u79f0')),
            ],
            options={
                'verbose_name': '\u673a\u6784\u7ba1\u7406',
                'verbose_name_plural': '\u673a\u6784\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u4eba\u5458\u540d\u79f0')),
                ('gender', models.CharField(choices=[('male', '\u7537'), ('femal', '\u5973')], max_length=6, verbose_name='\u6027\u522b')),
                ('phone', models.CharField(default='', max_length=11, verbose_name='\u7535\u8bdd\u53f7\u7801')),
                ('address', models.CharField(default='', max_length=100, verbose_name='\u4f4f\u5740')),
                ('ID_Card_NO', models.CharField(default='', max_length=18, verbose_name='\u8eab\u4efd\u8bc1\u53f7\u7801')),
                ('nation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comminfo.Nation')),
                ('organization', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cardcenter.Organization', verbose_name='\u6240\u5c5e\u673a\u6784')),
            ],
            options={
                'verbose_name': '\u4eba\u5458\u4fe1\u606f',
                'verbose_name_plural': '\u4eba\u5458\u4fe1\u606f',
            },
        ),
        migrations.AddField(
            model_name='card_for_personnel',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardcenter.Personnel', verbose_name='\u4eba\u5458\u4fe1\u606f'),
        ),
    ]
