# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardcenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u4eba\u5458\u540d\u79f0')),
                ('gender', models.CharField(choices=[('male', '\u7537'), ('femal', '\u5973')], max_length=6, verbose_name='\u6027\u522b')),
            ],
            options={
                'verbose_name': '\u4eba\u5458\u4fe1\u606f',
                'verbose_name_plural': '\u4eba\u5458\u4fe1\u606f',
            },
        ),
    ]
