# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardcenter', '0004_auto_20180706_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='nation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='comminfo.Nation'),
        ),
    ]
