# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-06 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardcenter', '0005_auto_20180706_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_for_personnel',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardcenter.Personnel', verbose_name='\u4eba\u5458\u4fe1\u606f'),
        ),
    ]
